// <auto-generated>
//     VSTO 프로젝트 시스템이 이 파일을 관리합니다.
//     Application, CustomTaskPanes, Startup/Shutdown 이벤트는
//     {BAA0C2D2-18E2-41B9-852F-F413020CAA33} 프로젝트 시스템이 제공합니다.
// </auto-generated>

namespace MailPrioritizer
{
    partial class ThisAddIn
    {
    }

    /// <summary>VSTO 전역 서비스 접근자.</summary>
    internal sealed partial class Globals
    {
        private Globals() { }

        internal static ThisAddIn ThisAddIn { get; set; }

        internal static Microsoft.Office.Tools.Outlook.Factory Factory { get; set; }
    }
}
