// <auto-generated>
//     VSTO 프로젝트 시스템이 이 파일을 관리합니다.
// </auto-generated>

namespace MailPrioritizer
{
    partial class ThisAddIn
    {
        protected virtual Microsoft.Office.Core.IRibbonExtensibility CreateRibbonExtensibilityObject()
        {
            return new Ribbon.MailRibbon();
        }
    }

    /// <summary>VSTO 전역 서비스 접근자.</summary>
    internal sealed partial class Globals
    {
        private Globals() { }

        internal static ThisAddIn ThisAddIn { get; set; }

        internal static Microsoft.Office.Tools.Outlook.Factory Factory { get; set; }
    }
}
