//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 VSTO 도구에서 생성했습니다.
//     런타임 버전: 4.0.30319.42000
//
//     이 파일을 수동으로 수정하면 오류가 발생할 수 있습니다.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414

namespace MailPrioritizer
{
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    public sealed partial class ThisAddIn :
        Microsoft.Office.Tools.Outlook.OutlookAddInBase
    {
        internal Microsoft.Office.Interop.Outlook.Application Application;
        internal Microsoft.Office.Tools.CustomTaskPaneCollection CustomTaskPanes;

        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ThisAddIn(global::Microsoft.Office.Tools.Outlook.Factory factory,
                         global::System.IServiceProvider serviceProvider) :
            base(factory, serviceProvider, "AddIn", "ThisAddIn")
        {
            Globals.Factory = factory;
        }

        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void Initialize()
        {
            base.Initialize();
            this.Application = this.GetHostItem<Microsoft.Office.Interop.Outlook.Application>(
                typeof(Microsoft.Office.Interop.Outlook.Application), "Application");
            this.CustomTaskPanes = this.CustomTaskPanesBase;
            Globals.ThisAddIn = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InternalStartup();
        }

        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FinishInitialization()
        {
            this.OnStartup();
        }

        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void OnShutdown()
        {
            base.OnShutdown();
        }
    }

    /// <summary>VSTO 런타임 인프라. 전역 서비스 접근자.</summary>
    [global::System.Runtime.InteropServices.ComVisible(false)]
    [global::System.ComponentModel.ToolboxItem(false)]
    public sealed partial class Globals
    {
        private static ThisAddIn s_ThisAddIn;
        private static global::Microsoft.Office.Tools.Outlook.Factory s_factory;

        private Globals()
        {
        }

        internal static ThisAddIn ThisAddIn
        {
            get { return s_ThisAddIn; }
            set { s_ThisAddIn = value; }
        }

        internal static global::Microsoft.Office.Tools.Outlook.Factory Factory
        {
            get { return s_factory; }
            set { s_factory = value; }
        }
    }
}
