//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 VSTO 도구에서 생성했습니다.
//     런타임 버전: 4.0.30319.42000
//
//     이 파일을 수동으로 수정하면 오류가 발생할 수 있습니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailPrioritizer.Ribbon
{
    partial class MailRibbon : Microsoft.Office.Tools.Ribbon.RibbonBase
    {
        /// <summary>Required designer variable.</summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>Clean up any resources being used.</summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.Name = "MailRibbon";
        }

        #endregion

        /// <summary>
        /// Ribbon XML 리소스를 반환한다.
        /// EmbeddedResource로 포함된 MailRibbon.xml을 읽어 Office 런타임에 전달.
        /// </summary>
        public override string GetCustomUI(string ribbonID)
        {
            return GetResourceText("MailPrioritizer.Ribbon.MailRibbon.xml");
        }

        private static string GetResourceText(string resourceName)
        {
            var asm = System.Reflection.Assembly.GetExecutingAssembly();
            string[] resourceNames = asm.GetManifestResourceNames();

            for (int i = 0; i < resourceNames.Length; i++)
            {
                if (string.Compare(resourceName, resourceNames[i],
                    System.StringComparison.OrdinalIgnoreCase) == 0)
                {
                    using (var reader = new System.IO.StreamReader(
                        asm.GetManifestResourceStream(resourceNames[i])))
                    {
                        if (reader != null)
                            return reader.ReadToEnd();
                    }
                    break;
                }
            }
            return null;
        }
    }
}
