// <auto-generated>
//     VSTO 도구에서 생성. 수동 수정 금지.
// </auto-generated>

namespace MailPrioritizer.Ribbon
{
    partial class MailRibbon
    {
        /// <summary>
        /// IRibbonExtensibility.GetCustomUI — EmbeddedResource에서 XML을 읽어 반환.
        /// </summary>
        public string GetCustomUI(string ribbonID)
        {
            return GetResourceText("MailPrioritizer.Ribbon.MailRibbon.xml");
        }

        private static string GetResourceText(string resourceName)
        {
            var asm = System.Reflection.Assembly.GetExecutingAssembly();
            foreach (string name in asm.GetManifestResourceNames())
            {
                if (string.Compare(resourceName, name,
                    System.StringComparison.OrdinalIgnoreCase) == 0)
                {
                    using (var reader = new System.IO.StreamReader(
                        asm.GetManifestResourceStream(name)))
                    {
                        return reader?.ReadToEnd();
                    }
                }
            }
            return null;
        }
    }
}
