// <auto-generated>
//     VSTO 도구에서 생성. 수동 수정 금지.
// </auto-generated>

namespace MailPrioritizer.Ribbon
{
    partial class MailRibbon : Microsoft.Office.Tools.Ribbon.RibbonBase
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        private void InitializeComponent()
        {
            this.Name = "MailRibbon";
        }

        #endregion

        /// <summary>
        /// VSTO XML Ribbon — EmbeddedResource에서 XML을 읽어 반환.
        /// RibbonBase.GetResourceText()를 override해서 XML 내용 전달.
        /// </summary>
        public override string GetResourceText(string resourceName)
        {
            var asm = System.Reflection.Assembly.GetExecutingAssembly();
            foreach (string name in asm.GetManifestResourceNames())
            {
                if (string.Compare(resourceName, name,
                    System.StringComparison.OrdinalIgnoreCase) == 0)
                {
                    using (var reader = new System.IO.StreamReader(
                        asm.GetManifestResourceStream(name)))
                    {
                        return reader?.ReadToEnd();
                    }
                }
            }
            return null;
        }
    }
}
